version: '3'

volumes:
  apollo.log:

services:
  apollo-configservice:
    image: polegek/apollo-configservice:1.5.1
    container_name: apollo-configservice
    network_mode: "host"
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      DS_URL: jdbc:mysql://mysql.address:3306/apolloconfigdb?characterEncoding=utf8
      DS_USERNAME: username
      DS_PASSWORD: password
    volumes: 
      - apollo.log:/opt/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  apollo-adminservice:
    image: polegek/apollo-adminservice:1.5.1
    container_name: apollo-adminservice
    network_mode: "host"
    depends_on:
      - apollo-configservice
    ports:
      - "8090:8090"
    environment:
      SERVER_PORT: 8090
      DS_URL: jdbc:mysql://mysql.address:3306/ApolloConfigDB?characterEncoding=utf8
      DS_USERNAME: username
      DS_PASSWORD: password
    volumes: 
      - apollo.log:/opt/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  apollo-portal:
    image: polegek/apollo-portal:1.5.1
    container_name: apollo-portal
    network_mode: "host"
    depends_on:
      - apollo-adminservice
    ports:
      - "8070:8070"
    environment:
      SERVER_PORT: 8070
      DS_URL: jdbc:mysql://mysql.address:3306/ApolloPortalDB?characterEncoding=utf8
      DS_USERNAME: username
      DS_PASSWORD: password
      LOCAL_META: "http://apollo-configservice:8080"
      DEV_META: ""
      FAT_META: ""
      UAT_META: ""
      LPT_META: ""
      PRO_META: ""
    volumes: 
      - apollo.log:/opt/logs
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

